version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: "llm-demo2-nginx"
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - "./nginx/index.html:/usr/share/nginx/html/index.html"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - "llm_demo2_network"

  rasa:
    build:
      context: "."
    container_name: "llm-demo2-rasa"
    restart: "always"
    volumes:
      - "./data:/app/data"
      - "./custom:/app/custom"
      - "./credentials.yml:/app/credentials.yml"
      - "./endpoints.yml:/app/endpoints.yml"
      - "./domain.yml:/app/domain.yml"
      - "./config.yml:/app/config.yml"
    networks:
      - "llm_demo2_network"
    env_file:
      - ".env"

networks:
  llm_demo2_network:
